### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by shahidge4** [l0gan/domainCat#3]
python3 domainCat.py --domain example.com
  File "domainCat.py", line 40
    print "\033[1;34m[*] Targeting McAfee Trustedsource\033[0;0m"
                                                                ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by l0gan** [comment]
Currently it is only Python2.7, but I have plans on updating to python3. Will work on this.

**Comment by linuxkd** [comment]
see PR that likely closes this issue via #!

**Comment by shahidge4** [comment]
root@demo:/opt/domainCat# python -V
Python 2.7.13
root@demo:/opt/domainCat#  python domainCat.py --domain pornhub.com
Traceback (most recent call last):
  File "domainCat.py", line 4, in <module>
    from modules import *
  File "/opt/domainCat/modules/bluecoat.py", line 4, in <module>
    import requests
ImportError: No module named requests
root@demo:/opt/domainCat#

**Comment by l0gan** [comment]
I merged in the changes to make this work with python3. Ensure you have requests and bs4 installed (I updated the readme as well) 
`pip3 install bs4
pip3 install requests`
Then run with python3 and see how that works for you.
