### ISSUE TITLE
Issue with bluecoat

### ISSUE THREAD

**Issue by krlplm** [l0gan/domainCat#6]
The bluecoat script fails with the below error,

<Response [422]>
[-] An error occurred
list index out of range

The above response is the one from below,
```
response = requests.post("http://sitereview.bluecoat.com/resource/lookup", headers=headers, json=data, cookies=cookies)
print(response)
```

**Comment by l0gan** [comment]
I just ran this and it works fine for me. check to see if it is still failing for you or not and respond back.
